name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Build Stage
      run: echo "Build Successful"

    - name: Test Stage
      run: echo "Test Successful"

  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master

      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}

        script: |
          cd /home/ec2-user/GitCICD-REPO
          git pull origin main
          pkill node || true
          nohup node app.js > output.log 2>&1 &





















 






















        
        
























































 
























